apiVersion: v1
kind: Service 
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: my-app
  ports: 
    - name: http
      port: 8001 # Service Port
      targetPort: 80 # Container Port